### ISSUE TITLE
Is this package meant to be shared with GopherJS users at large?

### ISSUE THREAD

**Issue by dmitshur** [oskca/gopherjs-canvas#1]
Hi @oskca, this looks like a nice package for the canvas part of the DOM API.

But it's not listed at https://github.com/gopherjs/gopherjs/wiki/Bindings, and some of the documentation is not English, making it hard to read for programmers who use English as a common language (not necessarily their native).

Is it your intent to make this library more generally useful and add it to the wiki page? If so, you should try to have docs be English.

If you prefer not to do that and want to keep this package for your own personal use, that's completely fine. I just wanted to ask and find out. I've found it via https://github.com/dominikh/go-js-dom/issues/43#issuecomment-323890259.

**Comment by dmitshur** [comment]
Did you see this question @oskca?

**Comment by oskca** [comment]
Yeah, I'd like to do that :smile:  @shurcooL 

I can try the re-documenting this week

**Comment by dmitshur** [comment]
I see, thanks for answering.

You might also find this commit interesting, https://github.com/dominikh/go-js-dom/commit/6a8015da13438f4de2c715e781271ab856b4b24c, just FYI.

**Comment by oskca** [comment]
I've done the re doc :smile:

**Comment by dmitshur** [comment]
Great!

In case you missed it, I'll point to this again:

> You might also find this commit interesting, https://github.com/dominikh/go-js-dom/commit/6a8015da13438f4de2c715e781271ab856b4b24c, just FYI.

If you don't want to apply the entire change, a minimal version to consider would be changing from using `color.RGBA` to `color.NRGBA`.

**Comment by oskca** [comment]
@shurcooL hi, i've done the converting from `color.RGBA` to `color.NRGBA`
When I was doing this wrapper library, `gopherjs` would produce huge output, so I tried to import as less library as possible(especially `dominikh/go-js-dom` which would increase the output js file size), so I wrap [a little library]("github.com/oskca/gopherjs-dom") to do the `dom` manipulation.

When I have time, perhaps I'll recheck the situation to use ` dominikh/go-js-dom` instead. :smile:
